#!/usr/bin/env python3
"""
TAISUN Agent 完全ガイド - Part 9-12の設定
"""

# Part 9: 業種別活用事例（12枚）
PART9_USECASES = [
    {"num": 70, "name": "p70_usecase_it_dev", "bg_prompt": "anime style illustration, robot developer team coding efficiently with automated reviews, development speed boost visualization, tech startup office, no text, high quality",
     "title_texts": [{"text": "【IT企業】開発効率化", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 80, 120, 255), "outline_width": 5}],
     "telop": "コードレビュー自動化で開発速度2倍、バグ80%削減"},
    {"num": 71, "name": "p71_usecase_it_test", "bg_prompt": "anime style illustration, robot running automated tests on multiple screens, test coverage visualization, quality assurance lab, green checkmarks, no text, high quality",
     "title_texts": [{"text": "【IT企業】テスト自動化", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 100, 50, 255), "outline_width": 5}],
     "telop": "E2Eテスト・単体テストを自動生成、カバレッジ向上"},
    {"num": 72, "name": "p72_usecase_marketing", "bg_prompt": "anime style illustration, marketer robot creating content rapidly, blog posts and social media flying, content production line, creative efficiency, no text, high quality",
     "title_texts": [{"text": "【マーケ】コンテンツ制作", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (200, 0, 100, 255), "outline_width": 5}],
     "telop": "ブログ・SNS・広告文を高速作成、A/Bテスト効率化"},
    {"num": 73, "name": "p73_usecase_research", "bg_prompt": "anime style illustration, analyst robot gathering market data and creating reports, research dashboard, competitive analysis, data visualization, no text, high quality",
     "title_texts": [{"text": "【マーケ】市場調査", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 80, 100, 255), "outline_width": 5}],
     "telop": "競合分析・トレンド調査・レポート作成を自動化"},
    {"num": 74, "name": "p74_usecase_consulting", "bg_prompt": "anime style illustration, consultant robot creating professional proposal documents, presentation slides floating, business meeting preparation, no text, high quality",
     "title_texts": [{"text": "【コンサル】提案書作成", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 60, 100, 255), "outline_width": 5}],
     "telop": "クライアント向け資料を高品質かつ高速に作成"},
    {"num": 75, "name": "p75_usecase_ec", "bg_prompt": "anime style illustration, e-commerce robot writing product descriptions, online shop visualization, SEO optimization, product catalog, no text, high quality",
     "title_texts": [{"text": "【EC事業者】商品説明文", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (200, 100, 0, 255), "outline_width": 5}],
     "telop": "魅力的な商品説明・SEO対策済み文章を自動生成"},
    {"num": 76, "name": "p76_usecase_realestate", "bg_prompt": "anime style illustration, real estate robot creating property listings, house descriptions floating, property showcase, professional presentation, no text, high quality",
     "title_texts": [{"text": "【不動産】物件紹介文", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 100, 80, 255), "outline_width": 5}],
     "telop": "物件の魅力を引き出す紹介文を効率的に作成"},
    {"num": 77, "name": "p77_usecase_legal", "bg_prompt": "anime style illustration, lawyer robot preparing legal documents, contracts and checklists, professional legal office, organized documentation, no text, high quality",
     "title_texts": [{"text": "【士業】契約書・書類作成", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (60, 60, 100, 255), "outline_width": 5}],
     "telop": "定型文書の下書き作成、チェックリスト自動生成"},
    {"num": 78, "name": "p78_usecase_education", "bg_prompt": "anime style illustration, teacher robot creating educational materials, textbooks and quizzes floating, classroom preparation, learning resources, no text, high quality",
     "title_texts": [{"text": "【教育】教材作成", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 100, 100, 255), "outline_width": 5}],
     "telop": "授業資料・問題集・解説文を効率的に作成"},
    {"num": 79, "name": "p79_usecase_video", "bg_prompt": "anime style illustration, video creator robot editing content, YouTube thumbnails floating, video production workflow, creative studio, no text, high quality",
     "title_texts": [{"text": "【クリエイター】動画制作", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (200, 0, 0, 255), "outline_width": 5}],
     "telop": "台本作成・サムネイル生成・説明文作成を支援"},
    {"num": 80, "name": "p80_usecase_blog", "bg_prompt": "anime style illustration, blogger robot writing articles rapidly, SEO optimization visualization, blog posts flying, content creation, no text, high quality",
     "title_texts": [{"text": "【ブロガー】記事執筆", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 150, 100, 255), "outline_width": 5}],
     "telop": "SEO対策済み記事・構成案・アイキャッチを自動生成"},
    {"num": 81, "name": "p81_usecase_startup", "bg_prompt": "anime style illustration, startup robot rapidly building MVP prototype, agile development visualization, fast iteration, launch countdown, no text, high quality",
     "title_texts": [{"text": "【スタートアップ】MVP開発", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (150, 0, 150, 255), "outline_width": 5}],
     "telop": "最小限の工数で動くプロトタイプを高速開発"},
]

# Part 10: 13層防御システム（8枚）
PART10_SECURITY = [
    {"num": 82, "name": "p82_security_why", "bg_prompt": "anime style illustration, warning scene showing AI risks without protection, data deletion files flying away, system crash visualization, danger atmosphere, no text, high quality",
     "title_texts": [{"text": "なぜセキュリティが重要？", "position": "top-center", "font_size": 48, "color": (255, 200, 200, 255), "outline_color": (150, 0, 0, 255), "outline_width": 5}],
     "telop": "AIの誤操作→データ削除・情報漏洩・システム破壊の危険"},
    {"num": 83, "name": "p83_security_overview", "bg_prompt": "anime style illustration, impressive 13 layer defense fortress visualization, multiple shield walls, guardian robot, impenetrable security concept, blue and gold defensive colors, no text, high quality",
     "title_texts": [{"text": "13層防御システム全体像", "position": "top-center", "font_size": 48, "color": (100, 200, 255, 255), "outline_color": (0, 40, 100, 255), "outline_width": 5}],
     "telop": "多層防御で1つが突破されても他が守る"},
    {"num": 84, "name": "p84_layer0", "bg_prompt": "anime style illustration, ultimate golden shield representing absolute rules, unbreakable law tablet, supreme protection, divine guardian concept, gold and white, no text, high quality",
     "title_texts": [{"text": "Layer 0: 絶対ルール", "position": "top-center", "font_size": 52, "color": (255, 220, 100, 255), "outline_color": (100, 60, 0, 255), "outline_width": 5}],
     "telop": "rm -rf / 禁止、秘密鍵操作禁止など絶対に破らないルール"},
    {"num": 85, "name": "p85_layer123", "bg_prompt": "anime style illustration, file protection shields surrounding important documents, locked folders, access control visualization, blue protective barriers, no text, high quality",
     "title_texts": [{"text": "Layer 1-3: ファイル保護", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 80, 120, 255), "outline_width": 5}],
     "telop": "重要ファイルの誤削除・上書きを防止"},
    {"num": 86, "name": "p86_layer456", "bg_prompt": "anime style illustration, command filter robot blocking dangerous commands, terminal with red warnings, command restriction visualization, security checkpoint, no text, high quality",
     "title_texts": [{"text": "Layer 4-6: コマンド制限", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (150, 80, 0, 255), "outline_width": 5}],
     "telop": "危険なコマンドの実行前に確認・ブロック"},
    {"num": 87, "name": "p87_layer789", "bg_prompt": "anime style illustration, environment variables and secrets protected in vault, locked safe with credentials, security vault visualization, green protective glow, no text, high quality",
     "title_texts": [{"text": "Layer 7-9: 環境保護", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 100, 60, 255), "outline_width": 5}],
     "telop": "環境変数・認証情報・設定ファイルを保護"},
    {"num": 88, "name": "p88_layer101112", "bg_prompt": "anime style illustration, quality inspector robot checking code and tests, quality gate with checkmarks, verification process, quality assurance checkpoint, no text, high quality",
     "title_texts": [{"text": "Layer 10-12: 品質ガード", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (100, 0, 100, 255), "outline_width": 5}],
     "telop": "コード品質・テスト・ドキュメントの整合性を確保"},
    {"num": 89, "name": "p89_security_custom", "bg_prompt": "anime style illustration, robot adjusting security settings on control panel, customization sliders, configuration options, personalized security, no text, high quality",
     "title_texts": [{"text": "防御システムのカスタマイズ", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 80, 100, 255), "outline_width": 5}],
     "telop": "プロジェクトに応じて防御レベルを調整可能"},
]

# Part 11: 要件定義（SDD）詳細（10枚）
PART11_SDD = [
    {"num": 90, "name": "p90_sdd_what", "bg_prompt": "anime style illustration, architect robot drawing detailed blueprints, requirements document visualization, planning before building concept, design phase, no text, high quality",
     "title_texts": [{"text": "要件定義とは何か？", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 80, 120, 255), "outline_width": 5}],
     "telop": "「何を作るか」を明確にする最重要工程"},
    {"num": 91, "name": "p91_sdd_why", "bg_prompt": "anime style illustration, failed project visualization with confused robot, unclear requirements causing problems, project failure scenario, warning atmosphere, no text, high quality",
     "title_texts": [{"text": "なぜ要件定義が重要？", "position": "top-center", "font_size": 48, "color": (255, 200, 200, 255), "outline_color": (150, 0, 0, 255), "outline_width": 5}],
     "telop": "要件定義の曖昧さがプロジェクト失敗の最大原因"},
    {"num": 92, "name": "p92_sdd_concept", "bg_prompt": "anime style illustration, SDD cycle diagram with spec document first then development, spec-driven development visualization, organized workflow, no text, high quality",
     "title_texts": [{"text": "SDD（Spec-Driven Dev）とは？", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (80, 0, 120, 255), "outline_width": 5}],
     "telop": "仕様書を先に書き、それに基づいて開発する手法"},
    {"num": 93, "name": "p93_cute_score", "bg_prompt": "anime style illustration, robot judge scoring requirements with CUTE metrics, score display panel, quality evaluation visualization, grading system, no text, high quality",
     "title_texts": [{"text": "C.U.T.E.スコアリング", "position": "top-center", "font_size": 52, "color": (255, 220, 100, 255), "outline_color": (100, 60, 0, 255), "outline_width": 5}],
     "telop": "Completeness・Unambiguity・Testability・EARSで品質評価"},
    {"num": 94, "name": "p94_completeness", "bg_prompt": "anime style illustration, checklist robot verifying all items covered, completeness check visualization, no gaps verification, thorough inspection, no text, high quality",
     "title_texts": [{"text": "【C】完全性 Completeness", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 100, 50, 255), "outline_width": 5}],
     "telop": "すべての要件が漏れなく記載されているか？"},
    {"num": 95, "name": "p95_unambiguity", "bg_prompt": "anime style illustration, clarity robot making vague text clear, ambiguous to clear transformation, precise language visualization, no text, high quality",
     "title_texts": [{"text": "【U】明確性 Unambiguity", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 80, 120, 255), "outline_width": 5}],
     "telop": "誰が読んでも同じ解釈になるか？"},
    {"num": 96, "name": "p96_testability", "bg_prompt": "anime style illustration, test robot verifying requirements can be tested, test case creation visualization, verifiable specifications, no text, high quality",
     "title_texts": [{"text": "【T】テスト可能性 Testability", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 100, 80, 255), "outline_width": 5}],
     "telop": "その要件をテストで確認できるか？"},
    {"num": 97, "name": "p97_ears", "bg_prompt": "anime style illustration, template robot filling in EARS format document, structured requirements writing, When The system shall format, organized documentation, no text, high quality",
     "title_texts": [{"text": "【E】EARS形式", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (150, 80, 0, 255), "outline_width": 5}],
     "telop": "When/The system shall/If-then形式で要件を記述"},
    {"num": 98, "name": "p98_template", "bg_prompt": "anime style illustration, robot presenting requirements document template, standardized format visualization, template showcase, professional documentation, no text, high quality",
     "title_texts": [{"text": "要件定義書のテンプレート", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 80, 100, 255), "outline_width": 5}],
     "telop": "TAISUN Agent標準の要件定義テンプレート"},
    {"num": 99, "name": "p99_ai_support", "bg_prompt": "anime style illustration, AI assistant robot helping improve requirements, detecting ambiguity and suggesting fixes, quality improvement visualization, helpful collaboration, no text, high quality",
     "title_texts": [{"text": "AIによる要件定義支援", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (80, 0, 120, 255), "outline_width": 5}],
     "telop": "曖昧な要件を自動検出→改善提案→スコア向上"},
]

# Part 12: まとめ（2枚）
PART12_SUMMARY = [
    {"num": 100, "name": "p100_future", "bg_prompt": "anime style illustration, successful robot surrounded by achievement icons, time saved money earned quality improved, bright future visualization, celebration atmosphere, no text, high quality",
     "title_texts": [{"text": "TAISUN Agentで実現する未来", "position": "top-center", "font_size": 44, "color": (255, 220, 100, 255), "outline_color": (100, 60, 0, 255), "outline_width": 5}],
     "telop": "作業時間80%削減・品質向上・収益アップを実現"},
    {"num": 101, "name": "p101_start", "bg_prompt": "anime style illustration, encouraging robot inviting viewer to start now, action call visualization, exciting beginning, motivational energy, welcoming atmosphere, no text, high quality",
     "title_texts": [{"text": "今すぐ始めよう！", "position": "top-center", "font_size": 60, "color": (255, 255, 255, 255), "outline_color": (0, 150, 100, 255), "outline_width": 6}],
     "telop": "たった6ステップでインストール完了！"},
]
