#!/usr/bin/env python3
"""
TAISUN Agent 完全ガイド - Part 5-12の設定
"""

# Part 5: スキルの詳細解説（12枚）
PART5_SKILLS = [
    {"num": 36, "name": "p36_skill_what", "bg_prompt": "anime style illustration, magical spell book with glowing command icons floating out, recipe book concept for programming, enchanted instruction manual, warm golden magic effects, no text, high quality",
     "title_texts": [{"text": "スキルとは何か？", "position": "top-center", "font_size": 56, "color": (255, 255, 255, 255), "outline_color": (120, 80, 0, 255), "outline_width": 5}],
     "telop": "特定タスクの「手順書」＋「ツール」のセット"},
    {"num": 37, "name": "p37_skill_how", "bg_prompt": "anime style illustration, robot typing slash command in terminal, command prompt with autocomplete suggestions, easy execution visualization, bright helpful interface, no text, high quality",
     "title_texts": [{"text": "スキルの呼び出し方", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 80, 120, 255), "outline_width": 5}],
     "telop": "/スキル名 で簡単に実行（例：/commit, /review-pr）"},
    {"num": 38, "name": "p38_skill_tdd", "bg_prompt": "anime style illustration, test cycle diagram red green refactor, scientist robot running experiments, quality assurance lab, testing workflow visualization, no text, high quality",
     "title_texts": [{"text": "【開発系】tdd-workflow", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 100, 50, 255), "outline_width": 5}],
     "telop": "テストファースト開発を強制、品質を担保"},
    {"num": 39, "name": "p39_skill_review", "bg_prompt": "anime style illustration, inspector robot checking code quality with checklist, magnifying glass on code, quality gate visualization, analytical atmosphere, no text, high quality",
     "title_texts": [{"text": "【開発系】code-review", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (100, 0, 100, 255), "outline_width": 5}],
     "telop": "品質・セキュリティ・保守性を自動レビュー"},
    {"num": 40, "name": "p40_skill_build", "bg_prompt": "anime style illustration, mechanic robot fixing error with wrench, error messages turning into success, repair visualization, workshop atmosphere, no text, high quality",
     "title_texts": [{"text": "【開発系】build-fix", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (150, 80, 0, 255), "outline_width": 5}],
     "telop": "ビルドエラーを検出→原因特定→修正を自動化"},
    {"num": 41, "name": "p41_skill_commit", "bg_prompt": "anime style illustration, robot creating git commit message, version control timeline visualization, save point concept, organized history, no text, high quality",
     "title_texts": [{"text": "【Git系】commit", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (200, 80, 0, 255), "outline_width": 5}],
     "telop": "変更内容を分析し、適切なコミットメッセージを生成"},
    {"num": 42, "name": "p42_skill_pr", "bg_prompt": "anime style illustration, robot creating pull request document, code comparison visualization, collaboration workflow, teamwork atmosphere, no text, high quality",
     "title_texts": [{"text": "【Git系】review-pr", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 100, 80, 255), "outline_width": 5}],
     "telop": "プルリクエストの作成・レビュー・マージを支援"},
    {"num": 43, "name": "p43_skill_research", "bg_prompt": "anime style illustration, detective robot researching with multiple browser windows, gathering information, investigation visualization, research atmosphere, no text, high quality",
     "title_texts": [{"text": "【調査系】research", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 80, 120, 255), "outline_width": 5}],
     "telop": "Web検索→情報収集→レポート作成を自動化"},
    {"num": 44, "name": "p44_skill_image", "bg_prompt": "anime style illustration, artist robot creating images from text prompts, AI image generation visualization, creative magic, colorful artistic atmosphere, no text, high quality",
     "title_texts": [{"text": "【画像系】nanobanana-pro", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (150, 0, 100, 255), "outline_width": 5}],
     "telop": "テキストから高品質なAI画像を生成"},
    {"num": 45, "name": "p45_skill_taiyo", "bg_prompt": "anime style illustration, marketing wizard robot with golden copywriting magic, persuasive text flowing, sales letter visualization, golden success aura, no text, high quality",
     "title_texts": [{"text": "【分析系】taiyo-analyzer", "position": "top-center", "font_size": 44, "color": (255, 220, 100, 255), "outline_color": (150, 80, 0, 255), "outline_width": 5}],
     "telop": "太陽スタイルに基づくコンテンツ品質分析"},
    {"num": 46, "name": "p46_skill_lp", "bg_prompt": "anime style illustration, conversion optimization robot analyzing landing page, A/B testing visualization, improvement arrows, marketing analytics atmosphere, no text, high quality",
     "title_texts": [{"text": "【文書系】lp-analysis", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 100, 100, 255), "outline_width": 5}],
     "telop": "ランディングページの成約率改善提案"},
    {"num": 47, "name": "p47_skill_list", "bg_prompt": "anime style illustration, grand library of 68 skill books organized by category, robot librarian showing catalog, impressive collection, organized knowledge, no text, high quality",
     "title_texts": [{"text": "68スキル一覧と使い分け", "position": "top-center", "font_size": 48, "color": (255, 220, 100, 255), "outline_color": (80, 40, 0, 255), "outline_width": 5}],
     "telop": "目的別にスキルを選んで組み合わせ"},
]

# Part 6: Macインストール（8枚）- 既存のものを使用
PART6_MAC = [
    {"num": 48, "name": "p48_mac_prep", "bg_prompt": "anime style illustration, cute robot with checklist preparing for Mac installation, MacBook on desk, system requirements floating, preparation atmosphere, no text, high quality",
     "title_texts": [{"text": "【Mac】インストール前の準備", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 80, 160, 255), "outline_width": 5}],
     "telop": "macOS 12以上、インターネット接続、管理者権限を確認"},
    {"num": 49, "name": "p49_mac_step1", "bg_prompt": "anime style illustration, robot pointing at Mac Finder window showing Applications Utilities Terminal path, step by step guide, helpful arrow pointing, no text, high quality",
     "title_texts": [{"text": "STEP 1", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "ターミナルを開く", "position": (30, 65), "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 80, 160, 255), "outline_width": 5}],
     "telop": "Finder →「アプリケーション」→「ユーティリティ」→「ターミナル」"},
    {"num": 50, "name": "p50_mac_step2", "bg_prompt": "anime style illustration, robot typing brew install command in terminal, Homebrew beer mug logo, installation progress, coding atmosphere, no text, high quality",
     "title_texts": [{"text": "STEP 2", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "Homebrewをインストール", "position": (30, 65), "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 100, 50, 255), "outline_width": 5}],
     "telop": "コマンド: /bin/bash -c \"$(curl -fsSL https://brew.sh/install.sh)\""},
    {"num": 51, "name": "p51_mac_step3", "bg_prompt": "anime style illustration, robot celebrating Node.js installation success, green Node.js hexagon logo, terminal showing success, achievement moment, no text, high quality",
     "title_texts": [{"text": "STEP 3", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "Node.jsをインストール", "position": (30, 65), "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 100, 50, 255), "outline_width": 5}],
     "telop": "コマンド: brew install node （約2分で完了）"},
    {"num": 52, "name": "p52_mac_step4", "bg_prompt": "anime style illustration, robot running npm install for Claude Code, purple Anthropic colors, installation progress bar, coding setup, no text, high quality",
     "title_texts": [{"text": "STEP 4", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "Claude Codeをインストール", "position": (30, 65), "font_size": 40, "color": (255, 255, 255, 255), "outline_color": (120, 60, 0, 255), "outline_width": 5}],
     "telop": "コマンド: npm install -g @anthropic-ai/claude-code"},
    {"num": 53, "name": "p53_mac_step5", "bg_prompt": "anime style illustration, robot cloning TAISUN from GitHub, cat mascot helping, git clone progress, download visualization, no text, high quality",
     "title_texts": [{"text": "STEP 5", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "TAISUN Agentをセットアップ", "position": (30, 65), "font_size": 40, "color": (255, 255, 255, 255), "outline_color": (80, 0, 120, 255), "outline_width": 5}],
     "telop": "コマンド: git clone → セットアップスクリプトを実行"},
    {"num": 54, "name": "p54_mac_step6", "bg_prompt": "anime style illustration, robot completing authentication with browser login success, celebration confetti, welcome screen, green checkmark, no text, high quality",
     "title_texts": [{"text": "STEP 6", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "初回認証を完了", "position": (30, 65), "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 120, 60, 255), "outline_width": 5}],
     "telop": "claude を実行 → ブラウザでAnthropicにログイン → 完了！"},
    {"num": 55, "name": "p55_mac_verify", "bg_prompt": "anime style illustration, robot checking version number on terminal screen, verification success, all systems go visualization, thumbs up, no text, high quality",
     "title_texts": [{"text": "【Mac】インストール確認", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 100, 80, 255), "outline_width": 5}],
     "telop": "claude --version でバージョンを確認"},
]

# Part 7: Windowsインストール（8枚）
PART7_WIN = [
    {"num": 56, "name": "p56_win_prep", "bg_prompt": "anime style illustration, cute robot with checklist preparing for Windows installation, Windows PC on desk, system requirements floating, preparation atmosphere, no text, high quality",
     "title_texts": [{"text": "【Win】インストール前の準備", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 100, 180, 255), "outline_width": 5}],
     "telop": "Windows 10/11、インターネット接続、管理者権限を確認"},
    {"num": 57, "name": "p57_win_step1", "bg_prompt": "anime style illustration, robot pointing at Windows Start menu search for PowerShell, right click context menu, admin execution, helpful guide, no text, high quality",
     "title_texts": [{"text": "STEP 1", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "PowerShellを開く", "position": (30, 65), "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 80, 160, 255), "outline_width": 5}],
     "telop": "スタート →「PowerShell」検索 → 右クリック →「管理者として実行」"},
    {"num": 58, "name": "p58_win_step2", "bg_prompt": "anime style illustration, robot browsing Node.js website on Windows, download button highlighted, green Node.js logo, browser download, no text, high quality",
     "title_texts": [{"text": "STEP 2", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "Node.jsをダウンロード", "position": (30, 65), "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 100, 50, 255), "outline_width": 5}],
     "telop": "nodejs.org にアクセス →「LTS版」をダウンロード"},
    {"num": 59, "name": "p59_win_step3", "bg_prompt": "anime style illustration, robot clicking Next button on Windows installer wizard, easy installation, progress bar, simple setup, no text, high quality",
     "title_texts": [{"text": "STEP 3", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "インストーラーを実行", "position": (30, 65), "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (0, 100, 50, 255), "outline_width": 5}],
     "telop": "ダウンロードしたファイルを開く →「Next」を押し続ける"},
    {"num": 60, "name": "p60_win_step4", "bg_prompt": "anime style illustration, robot running npm command in PowerShell blue window, Claude Code installation, purple Anthropic accents, no text, high quality",
     "title_texts": [{"text": "STEP 4", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "Claude Codeをインストール", "position": (30, 65), "font_size": 40, "color": (255, 255, 255, 255), "outline_color": (120, 60, 0, 255), "outline_width": 5}],
     "telop": "コマンド: npm install -g @anthropic-ai/claude-code"},
    {"num": 61, "name": "p61_win_step5", "bg_prompt": "anime style illustration, robot setting up TAISUN on Windows, PowerShell showing setup script, configuration files, blue and gold colors, no text, high quality",
     "title_texts": [{"text": "STEP 5", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "TAISUN Agentをセットアップ", "position": (30, 65), "font_size": 40, "color": (255, 255, 255, 255), "outline_color": (80, 0, 120, 255), "outline_width": 5}],
     "telop": "セットアップコマンドを実行してTAISUNを導入"},
    {"num": 62, "name": "p62_win_step6", "bg_prompt": "anime style illustration, robot completing Windows authentication for Claude, Edge browser showing login success, celebration effects, green checkmark, no text, high quality",
     "title_texts": [{"text": "STEP 6", "position": (30, 25), "font_size": 32, "color": (100, 200, 255, 255), "outline_color": (0, 50, 100, 255), "outline_width": 3},
                    {"text": "初回認証を完了", "position": (30, 65), "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 120, 60, 255), "outline_width": 5}],
     "telop": "claude を実行 → ブラウザでAnthropicにログイン → 完了！"},
    {"num": 63, "name": "p63_win_verify", "bg_prompt": "anime style illustration, robot verifying version on Windows PowerShell, all systems operational, success confirmation, thumbs up, no text, high quality",
     "title_texts": [{"text": "【Win】インストール確認", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 100, 80, 255), "outline_width": 5}],
     "telop": "claude --version でバージョンを確認"},
]

# Part 8: アップデートと管理（6枚）
PART8_UPDATE = [
    {"num": 64, "name": "p64_update_why", "bg_prompt": "anime style illustration, robot upgrading with new features being added, version update visualization, improvement arrows, evolution concept, no text, high quality",
     "title_texts": [{"text": "アップデートの重要性", "position": "top-center", "font_size": 52, "color": (255, 255, 255, 255), "outline_color": (0, 100, 80, 255), "outline_width": 5}],
     "telop": "新機能追加・バグ修正・セキュリティ強化のため定期更新を"},
    {"num": 65, "name": "p65_update_claude", "bg_prompt": "anime style illustration, robot running npm update command, package update visualization, version number incrementing, upgrade process, no text, high quality",
     "title_texts": [{"text": "Claude Codeのアップデート", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (120, 60, 0, 255), "outline_width": 5}],
     "telop": "コマンド: npm update -g @anthropic-ai/claude-code"},
    {"num": 66, "name": "p66_update_taisun", "bg_prompt": "anime style illustration, robot pulling latest code from repository, git pull visualization, sync with remote, update flow, no text, high quality",
     "title_texts": [{"text": "TAISUN Agentのアップデート", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (80, 0, 120, 255), "outline_width": 5}],
     "telop": "コマンド: cd ~/.claude && git pull origin main"},
    {"num": 67, "name": "p67_multi_project", "bg_prompt": "anime style illustration, robot managing multiple project folders organized neatly, folder structure visualization, separate configurations, organized workspace, no text, high quality",
     "title_texts": [{"text": "複数プロジェクトでの管理", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (0, 80, 120, 255), "outline_width": 5}],
     "telop": "プロジェクトごとに .claude フォルダで設定を分離"},
    {"num": 68, "name": "p68_project_settings", "bg_prompt": "anime style illustration, robot editing project settings file, configuration JSON visualization, customization options, settings panel, no text, high quality",
     "title_texts": [{"text": "プロジェクト別設定の作り方", "position": "top-center", "font_size": 44, "color": (255, 255, 255, 255), "outline_color": (100, 80, 0, 255), "outline_width": 5}],
     "telop": ".claude/settings.json でプロジェクト固有の設定"},
    {"num": 69, "name": "p69_troubleshoot", "bg_prompt": "anime style illustration, robot doctor diagnosing and fixing common errors, troubleshooting flowchart, problem solving, help desk atmosphere, no text, high quality",
     "title_texts": [{"text": "トラブルシューティング", "position": "top-center", "font_size": 48, "color": (255, 255, 255, 255), "outline_color": (150, 0, 0, 255), "outline_width": 5}],
     "telop": "よくあるエラーと解決方法一覧"},
]
