import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { AbstractTool } from "./AbstractTool.js";
import { createSuccessResponse, createErrorResponse } from "../common/response.js";
import type { LeadStore } from "../storage/lead-store.js";
import { SequenceEngine } from "../outreach/sequence-engine.js";
import { createSequenceForRank } from "../outreach/channel-router.js";

const StepSchema = z.object({
  stepNumber: z.number().describe("ステップ番号"),
  channel: z.enum(["line", "email", "sms", "voice"]).describe("チャネル"),
  delayHours: z.number().describe("前ステップからの待機時間(時間)"),
  messageTemplate: z.string().describe("テンプレートキー"),
});

export default class CreateSequenceTool extends AbstractTool {
  private readonly leadStore: LeadStore;
  private readonly sequenceEngine: SequenceEngine;

  constructor(leadStore: LeadStore, sequenceEngine: SequenceEngine) {
    super();
    this.leadStore = leadStore;
    this.sequenceEngine = sequenceEngine;
  }

  register(server: McpServer): void {
    server.tool(
      "sdr_create_sequence",
      "リード向けのアウトリーチシーケンスを作成。ステップ未指定時はランクに基づく自動生成。",
      {
        leadId: z.string().describe("リードID"),
        name: z.string().optional().describe("シーケンス名"),
        steps: z
          .array(StepSchema)
          .optional()
          .describe("カスタムステップ (省略時はランク別自動生成)"),
      },
      async ({ leadId, name, steps }) => {
        try {
          const lead = this.leadStore.getLeadById(leadId);
          if (!lead) {
            return createErrorResponse(`リードが見つかりません: ${leadId}`);
          }

          const sequenceSteps = steps
            ? steps.map((s) => ({
                ...s,
                status: "pending" as const,
              }))
            : createSequenceForRank(lead.rank);

          const sequence = this.sequenceEngine.createSequence(
            lead,
            sequenceSteps,
            name
          );

          return createSuccessResponse({
            message: `シーケンスを作成しました: ${sequence.name}`,
            sequence,
            totalSteps: sequence.steps.length,
            autoGenerated: steps === undefined,
          });
        } catch (error) {
          const msg =
            error instanceof Error ? error.message : String(error);
          return createErrorResponse(`シーケンス作成失敗: ${msg}`);
        }
      }
    );
  }
}
